# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      publishNativePlugin:
        description: 'Publish the native plugin?'
        default: 'false'
        required: true
      publishGradlePlugin:
        description: 'Publish the Gradle plugin?'
        default: 'false'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runs-on: ubuntu-latest:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Publish Native Plugin
        if: github.event.inputs.publishNativePlugin == "true"
        run: ./gradlew bintrayUpload --no-daemon --stacktrace
        env:
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      - name: Publish Gradle Plugin
        if: github.event.inputs.publishGradlePlugin == "true"
        run: ./gradlew publishPlugins --no-daemon --stacktrace
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
